### ISSUE TITLE
Factom and Maidsafe Integration

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-framework#38]
sry, somehow i edited this comment and now i have no idea what it said before.... os

**Comment by OR13** [comment]
I think this should probably be implemented after IPFS. The reason being, when we start to add events from storage, we want that interface to support all future storage systems. IPFS is easier to implement, I've wrapped it before at the hackathon. IPFS is also offered on Infura, and since we are already gratefully using Infura for ropsten access...

@eolszewski

**Comment by OR13** [comment]
This should be done first https://github.com/transmute-industries/transmute-framework/issues/39
