### ISSUE TITLE
isAuthorizedEvent is a confusing name

### ISSUE THREAD

**Issue by illuzen** [transmute-industries/transmute-framework#69]
Because it seems to refer to whether or not it's a permissioned event at all. So the modifier can be bypassed by setting isAuthorizedEvent == false...maybe I'm misunderstanding how to use this thing.

`  modifier onlyWriteAuthorized(bool _isAuthorizedEvent, bytes32 _permissionDomain) {
    require(!_isAuthorizedEvent || (ACLAddresses.contains(tx.origin) && ACLMapping[tx.origin][_permissionDomain].write));
    _;
  }`

**Comment by OR13** [comment]
@illuzen I completely agree.

The issue here is that often we want to allow a user to request permissions. 

The event that represents this request needs to allow anonymous access.

I think the ordering here might be the source of confusion:

_isEventAuthorized might be clearer.

_isEventAnonymousAccess

_isEventUnprotected

etc...

Please suggest any others if you can think of better.

**Comment by illuzen** [comment]
I guess I don't really understand how it should be used since the bool is passed into the function and the function is public, so anyone can bypass the require check by passing _isAuthorizedEvent == false.

**Comment by eolszewski** [comment]
So the function should be internal - that's a faux pas on my part. 

@illuzen - With events, you have authorized and unauthorized events. In order to write an authorized event for a specific domain, you need to have someone who is authorized to do so in said domain. So, the first guy to get access to this domain will have to leverage unauthorized events to do so (given there is nobody with read or write access for that domain). 

So, you'll absolutely need to bypass that modifier initially to give access to the first addresses for a domain. And if you decide to not have read / write permissions on events, you can just keep them as unauthorized and proceed without it. 

Does this make sense?

**Comment by OR13** [comment]
@illuzen thanks for pointing this out. This approach needs a rework.

There are a couple concerns I have after reviewing the tests:

- Data poisoning, where an unauthorized user writes events that look like permission events.
- DAC for known addresses. (seems there should be some hardcoded values here...)
- Semantics 

The permission domain is an interesting idea, but the problem is that it needs to be properly combined with the concept of internal and external events (these are new concepts, i'll define below).

external events are a way for a smart contract to learn about a state change the happened outside of ethereum.

internal events are a way to record a state change that happened inside of ethereum.

consider the case of a single admin user identified by address.

The permission methods must use internal events to signal state change. 

internal and external events must be distinguishable and immutable.

In this way, and admin can use public methods to extend authorization to other users, but an anonymous adversary cannot use public methods to write events that look like internal ones.

Another solution might be to make 2 event streams, one for external events which can be written to by anyone who is authorized. And one for recording permissions changes, that can only be written to by the Contract or its children, and not by random unauthorized people.

**Comment by OR13** [comment]
On second thought, I think one event stream is sufficient, but probably there needs to be different signatures for writing solidity events as internal or external.

**Comment by illuzen** [comment]
Well, one way to see the problem is that there's no way to give different permissions for different types of events. As it is written, it would have given anybody the ability to edit content without going thru peer review.

Not sure what layer event discrimination should happen at, I'm guessing before this function gets called. Maybe there should be an enum of event types that somehow connects to permission domains? 

Also, I don't think you want to use tx.origin. It's a security issue: https://solidity.readthedocs.io/en/develop/security-considerations.html?highlight=tx.origin#tx-origin

**Comment by illuzen** [comment]
I'm not sure the fact it's public makes a big difference once it's a library, since everything will execute in the caller's context?

**Comment by OR13** [comment]
@illuzen Thanks for this thoughtful feedback, sorry I am responding to it so late.

I think the whole permissions model for each kind of event was not the right approach, and instead opted for an attribute based model... can <role> take <action> on <resource>... these grants are much more flexible, but the security of this approach is still in the progress of being evaluated.

I'm working on an update regarding tx origin, thanks for that link.

**Comment by OR13** [comment]
https://github.com/transmute-industries/transmute-framework/pull/76

**Comment by OR13** [comment]
I'm going to close this, as the rewrite changed pretty much everything.
